# Generated by Django 3.1.4 on 2020-12-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pic', models.ImageField(upload_to='')),
                ('about', models.CharField(blank=True, max_length=250, null=True)),
                ('git', models.URLField()),
                ('link', models.URLField()),
            ],
        ),
    ]
