# Generated by Django 3.1.5 on 2021-01-19 18:08

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Tanmay_Creates', '0002_auto_20201220_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
