# Generated by Django 3.1.5 on 2021-01-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tanmay_Creates', '0003_pageform'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageform',
            name='email',
            field=models.EmailField(default='tanmay', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pageform',
            name='name',
            field=models.CharField(default='tanmayvij11@gmail.com', max_length=560),
            preserve_default=False,
        ),
    ]
