# Generated by Django 3.1.5 on 2021-01-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tanmay_Creates', '0004_auto_20210120_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageform',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
